<!--
Start of DoubleClick Floodlight Tag: Please do not remove
Activity name of this tag: Shopping Cart
URL of the webpage where the tag is expected to be placed: http://www.vervecycling.com
This tag must be placed between the <body> and </body> tags, as close as possible to the opening tag.
Creation Date: 05/07/2015
-->
<script type="text/javascript">
    var axel = Math.random() + "";
    var a = axel * 10000000000000;
    document.write('<iframe src="https://4854312.fls.doubleclick.net/activityi;src=4854312;type=invmedia;cat=xkkqmdqs;ord=' + a + '?" width="1" height="1" frameborder="0" style="display:none"></iframe>');
</script>
<noscript>
    <iframe src="https://4854312.fls.doubleclick.net/activityi;src=4854312;type=invmedia;cat=xkkqmdqs;ord=1?" width="1" height="1" frameborder="0" style="display:none"></iframe>
</noscript>
<!-- End of DoubleClick Floodlight Tag: Please do not remove -->