<?php /* @var $this Mage_Checkout_Block_Onepage_Progress */ ?>
<div class="block-progress opc-block-progress">
    <div class="block-title">
        <span><?php echo $this->__('Your Purchase Details') ?></span>
    </div>
    <div class="block-content">
        <dl>
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
	        <?php if ($this->isStepComplete('billing')): ?>
	            <dt class="complete">
	                <?php echo $this->__('Billing Address') ?>
	            </dt>
	            <dd class="complete">
	            	<div class="address">
		                <address><?php echo $this->getBilling()->format('html') ?></address>
		                 <a class="change" href="#billing" onclick="checkout.gotoSection('billing'); return false;"><?php echo $this->__('Change details') ?></a>
	                </div>
			        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
				        <?php if ($this->isStepComplete('billing')): ?>
			                <h3 class="dt"><?php echo $this->__('Shipping Address') ?></h3>
			                <div class="shipping-address">
								<?php if($this->getQuote()->getShippingAddress()->getData('same_as_billing')):?>
				                <p><?php echo $this->__('Same as billing address')?></p>
				                <?php else:?>
				                <address><?php echo $this->getShipping()->format('html') ?></address>
				                <?php endif;?>
				                <a class="change" href="#billing" onclick="checkout.gotoSection('billing');return false;"><?php echo $this->__('Change details') ?></a>
			                </div>
				        <?php endif; ?>
			        <?php endif; ?>
	            </dd>
	        <?php else: ?>
	            <dt>
	                <?php echo $this->__('Billing & Shipping Address') ?>
	            </dt>
	        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
        <?php if ($this->isStepComplete('shipping_method')): ?>
            <dt class="complete">
                <?php echo $this->__('Shipping Method') ?>
            </dt>
            <dd class="complete">
                <?php if ($this->getShippingMethod()): ?>
                    <?php $description = $this->escapeHtml($this->getShippingDescription()) ?>
                    <?php
                    if(strpos($description,'-') !== false)
                        echo '<strong>'.preg_replace('/\-/', '</strong><br>', $description, 1)
                    ?>
                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo $this->__('Shipping method has not been selected yet') ?>
                <?php endif; ?>
                    <br>    
                    <a class="change" href="#shipping_method" onclick="checkout.gotoSection('shipping_method'); return false;"><?php echo $this->__('Change details') ?></a>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Shipping Method') ?>
            </dt>
        <?php endif; ?>

        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <?php if ($this->isStepComplete('payment')): ?>
            <dt class="complete">
                <?php echo $this->__('Payment Method') ?>
            </dt>
            <dd class="complete">
                <?php echo $this->getPaymentHtml() ?>
				<a class="change" href="#payment" onclick="checkout.gotoSection('payment'); return false;"><?php echo $this->__('Change details') ?></a>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Payment Method') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>
        </dl>
		<script type="text/javascript">
		<!--
			function progressControlFix(_this){
				if(jQuery('.col-main').css('float') == 'none'){
					event.preventDefault();
					targetId = jQuery(_this).attr('href');
					targetId = targetId.replace('#', '#ops-');
					if(jQuery(targetId).size()){
						targetY = jQuery(targetId).offset().top;
						if(targetY){
							targetY -= jQuery('.top-navigation').outerHeight() + 30;
						}else{
							 targetY = 0;
						}
						jQuery('html, body').animate({scrollTop: targetY}, 500);
					}
				}
				return false;			
			}	
		//-->
		</script>
    </div>
</div>
