
    <div class="contact pull-right">
        <h3 class="title">HAVE A QUESTION?</h3>
        <form action="" id="have-question" method="post" enctype="multipart/form-data">
            <div class="input-group input-contact">
                <input type="text" class="form-control required-entry" style="border-radius: 3px;" placeholder="Name*" aria-describedby="basic-addon1">
            </div>
            <div class="input-group input-contact">
                <input type="email" name="email" class="form-control required-entry validate-email" style="border-radius: 3px;" placeholder="Email*" aria-describedby="basic-addon1">
            </div>
            <!-- <input type="email" placeholder="EMAIL/PHONE*" required> -->
            <textarea style="border-radius: 3px; border: 1px solid #878787;" name="message" class="required-entry" cols="30" rows="10" placeholder="Message*"></textarea>
            <input type="submit" value="Ask Us!">
        </form>
    </div><!--end-contact-->

<script type="text/javascript">
     //<![CDATA[
        var customForm = new VarienForm('have-question');
     //]]>
</script>