<div class="testimonials">
    <div class="container" >
        <h2 class="tite">Testimonies</h2>
        <div id="testimoni-carousel" class="pull-left" style="width:94%; margin:auto;padding-left: 12px;">
            <div class="item">
                <div >
                    <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                </div>
                <h3 class="profile-name">SARAH STOREY</h3>
                <span class="win">72 TIME WORLD CHAMPION</span>
                <div class="quote">
                    <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                </div>
            </div>
            <div class="item">
                <div >
                    <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                </div>
                <h3 class="profile-name">SARAH STOREY</h3>
                <span class="win">72 TIME WORLD CHAMPION</span>
                <div class="quote">
                    <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                </div>
            </div>
            <div class="item">
                <div >
                    <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                </div>
                <h3 class="profile-name">SARAH STOREY</h3>
                <span class="win">72 TIME WORLD CHAMPION</span>
                <div class="quote">
                    <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                </div>
            </div>
            <div class="item">
                <div >
                    <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                </div>
                <h3 class="profile-name">SARAH STOREY</h3>
                <span class="win">72 TIME WORLD CHAMPION</span>
                <div class="quote">
                    <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                </div>
            </div>
            <div class="item">
                <div >
                    <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                </div>
                <h3 class="profile-name">SARAH STOREY</h3>
                <span class="win">72 TIME WORLD CHAMPION</span>
                <div class="quote">
                    <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                </div>
            </div>
            <div class="item">
                <div >
                    <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                </div>
                <h3 class="profile-name">SARAH STOREY</h3>
                <span class="win">72 TIME WORLD CHAMPION</span>
                <div class="quote">
                    <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                </div>
            </div>
            <div class="item">
                <div >
                    <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                </div>
                <h3 class="profile-name">SARAH STOREY</h3>
                <span class="win">72 TIME WORLD CHAMPION</span>
                <div class="quote">
                    <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                </div>
            </div>
            <div class="item">
                <div >
                    <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                </div>
                <h3 class="profile-name">SARAH STOREY</h3>
                <span class="win">72 TIME WORLD CHAMPION</span>
                <div class="quote">
                    <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                </div>
            </div>
        </div>
    </div>
</div><!--end-testimpnials-->