<?php
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 */
$_websites = Mage::app()->getWebsites();
foreach($_websites as $website)
{
    $storeId = $website->getDefaultGroup()->getDefaultStore()->getId();
    foreach(Mage::app()->getStore($storeId)->getAvailableCurrencyCodes() as $symbol)
    {
        $currencies[$symbol] = Mage::app()->getLocale()->currency($symbol)->getName();
    }
}
?>
<?php //if($this->getCurrencyCount()>1): ?>
<?php if(count($currencies)>1): ?>
<div class="product-currency" data-current-url="<?php echo $this->helper("core/url")->getCurrentUrl();?>">
    <div class="sub-title"><?php echo $this->__('PRICE:') ?> <span class="name">&nbsp;</span> <a href="javascript:;" onclick="currencyLisShow(this)"><?php echo $this->__('(Change currency)')?></a></div>
    <ul class="currency-list">

    <?php foreach ($currencies as $_code => $_name): ?>
        <li class="item<?php echo ($_code==$this->getCurrentCurrencyCode())? ' current':''; ?>" data-currency="<?php echo $this->getSwitchCurrencyUrl($_code) ?>">
			<a href="<?php //echo $this->getSwitchCurrencyUrl($_code) ?>" data-currency="<?php echo $_code?>">
			    <img src="<?php echo $this->getSkinUrl().'images/flag/' . strtolower($_code) . '.jpg'; ?>" title="<?php echo $_name ?> (<?php echo $_code ?>)" width="22" height="16" />
			    <span class="name"><?php echo $this->__($_name); ?></span> <span>(<?php echo Mage::app()->getLocale()->currency($_code)->getSymbol() ?>)</span>
			</a>
        </li>
    <?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>