<?php if ($detailedInfoGroup = $this->getChildGroup('product_tabs', 'getChildHtml')):?>
<?php $countTabs = (count($detailedInfoGroup)); ?>
    <dl id="collateral-tabs" class="collateral-tabs">
    <?php $i = 1; ?>
	<?php foreach ($detailedInfoGroup as $alias => $html):?>
        <dt class="tab<?php if($i == 1) echo ' active first'; if($i == $countTabs) echo ' last'; ?>"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
        <dd class="tab-container <?php echo $alias; if($i == 1) echo ' active'; ?>">
           <div class="tab-content"><?php echo $html ?></div>
        </dd>
	<?php ++$i; ?>
    <?php endforeach;?>
    </dl>
    <script type="text/javascript">
    //<![CDATA[
		styleProductTabs();
		jQuery('#collateral-tabs').children('dt').children('span').click(function(){
			var $dtTab = jQuery(this).parent();
			if(jQuery('#collateral-tabs').hasClass('mobile')){
				$dtTab.toggleClass('active');
				$dtTab.next('dd').toggleClass('active').slideToggle();
			}else{
				$dtTab.siblings().removeClass('active');
				$dtTab.addClass('active');
				$dtTab.next('dd').addClass('active');
			}
		});
		function collateralTabsTablet(){
			$dtWidht = 0;
			$collateralTabs = jQuery('#collateral-tabs');
			$collateralTabsDt = $collateralTabs.children('dt');
			$collateralTabsDt.each(function(){
				$dtWidht += parseInt(jQuery(this).children('span').outerWidth(true)) + parseInt(jQuery(this).css('padding-left')) + parseInt(jQuery(this).css('padding-right'));
			});
			if($dtWidht > ($collateralTabs.width() + 10)){
				$collateralTabs.addClass('tablet');
			}else{
				$collateralTabs.removeClass('tablet');
			}
			console.log($dtWidht > ($collateralTabs.width()+ 10));
			console.log($collateralTabs.width() + '  ' + $dtWidht);
			//console.log($dtWidht);
		}
		

		//collateralTabsTablet();

		
		jQuery(window).resize(function(){
			//collateralTabsTablet();
		});
    //]]>
    </script>
<?php endif; ?>