<div class="row rowpopupboxiii" style="padding-bottom: 51px;">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="featured-brand">
    <div class="">
        <ul>
            <li><a href="#!" style="margin-right: 68px;"><img src="<?php echo $this->getSkinUrl(); ?>images/b.png" alt=""></a></li>
            <li><a href="#!"><img src="<?php echo $this->getSkinUrl(); ?>images/h.png" alt="" style="width: 140px;"></a></li>
            <li><a href="#!"><img src="<?php echo $this->getSkinUrl(); ?>images/p.png" alt="" style="width: 180px;"></a></li>
            <li><a href="#!"><img src="<?php echo $this->getSkinUrl(); ?>images/WAIS.gif" alt="" style="width: 131px;"></a></li>
            <li><a href="#!" style="margin-right: 0px;"><img src="<?php echo $this->getSkinUrl(); ?>images/logo1.png" alt="" style="width: 155px;"></a></li>
        </ul>
    </div>
</div><!--end-featured-brand-->
    </div></div>