<section id="content">
    <ul class="nav nav-tabs tab-menu">
        <li role="presentation" class="active"><a href="#!" class="active"><span>INFOCRANK</span></a></li>
        <li role="presentation"><a href="#!"><span>PARTS AND ACCECORIES</span></a></li>
    </ul>
    <div class="tab-content">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-4">
                    <div class="product">
                        <h3 class="product-title"><a href="#!">Info Crank Compact M30</a></h3>
                        <ul class="review">
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!">Read the Review ></a></li>
                        </ul>
                        <span class="product-status">In Stock</span>
                        <div class="product-images product1">

                        </div>
                        <ul class="detail-product">
                            <li><i class="fa fa-bolt"></i>Left and Right power meter crankset</li>
                            <li><i class="fa fa-bolt"></i>Compact 110mm BCD spider</li>
                            <li><i class="fa fa-bolt"></i>Stiff M30 axle, ships with Praxis Works
                                bottom bracket</li>
                            <li><i class="fa fa-bolt"></i>Road chainring options include: Praxis
                                compact 50/34, Praxis mid-compact 52/36,
                                or TA Syrius 53/39</li>
                        </ul>
                        <strong class="product-price">$1,750</strong>
                        <div class="product-action">
                            <ul>
                                <li><a href="#!" class="detail">view details <i class="fa fa-plus-circle"></i></a></li>
                                <li><a href="#!" class="order">Place order <i class="fa fa-shopping-cart"></i></a></li>
                            </ul>
                        </div>
                    </div><!--end-product-->
                </div>
                <div class="col-xs-12 col-md-4">
                    <div class="product">
                        <h3 class="product-title"><a href="#!">Info Crank Clasic Standard</a></h3>
                        <ul class="review">
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!" class="star"><i class="fa fa-star"></i></a></li>
                            <li><a href="#!">Read the Review ></a></li>
                        </ul>
                        <span class="product-status">In Stock</span>
                        <div class="product-images product2">

                        </div>
                        <ul class="detail-product">
                            <li><i class="fa fa-bolt"></i>Left and Right power meter crankset</li>
                            <li><i class="fa fa-bolt"></i>Standard 130mm BCD spider</li>
                            <li><i class="fa fa-bolt"></i>24mm spindle, fits standard 24mm bottom
                                brackets (Shimano™ recommended)</li>
                            <li><i class="fa fa-bolt"></i>Supplied with Praxis standard 53/39 Road
                                chainrings</li>
                        </ul>
                        <strong class="product-price">$1,750</strong>
                        <div class="product-action">
                            <ul>
                                <li><a href="#!" class="detail">view details <i class="fa fa-plus-circle"></i></a></li>
                                <li><a href="#!" class="order">Place order <i class="fa fa-shopping-cart"></i></a></li>
                            </ul>
                        </div>
                    </div><!--end-product-->
                </div>
                <div class="col-xs-12 col-md-4">
                    <div class="contact pull-right">
                        <h3 class="title">HAVE A QUESTION?</h3>
                        <form action="" style="/*background-color: #EEEEEE;*/">
                            <div class="input-group input-contact">
                                <input type="text" class="form-control" style="border-radius: 3px" placeholder="Name*" aria-describedby="basic-addon1">
                            </div>
                            <div class="input-group input-contact">
                                <input type="email" class="form-control " style="border-radius: 3px" placeholder="Email*" aria-describedby="basic-addon1">
                            </div>
                            <!-- <input type="email" placeholder="EMAIL/PHONE*" required> -->
                            <textarea style="border-radius: 3px; border: 1px solid #878787;" name="" id="" cols="30" rows="10" placeholder="Message"></textarea>
                            <input type="submit" value="Ask Us!">
                        </form>
                    </div><!--end-contact-->
                </div>
            </div>
        </div>
    </div><!--end-tab-content-->
    <div class="featured-brand">
        <div class="container">
            <ul>
                <li><a href="#!" style="margin-right: 88px;"><img src="<?php echo $this->getSkinUrl(); ?>images/b.png" alt=""></a></li>
                <li><a href="#!"><img src="<?php echo $this->getSkinUrl(); ?>images/h.png" alt="" style="width: 140px;"></a></li>
                <li><a href="#!"><img src="<?php echo $this->getSkinUrl(); ?>images/p.png" alt="" style="width: 180px;"></a></li>
                <li><a href="#!"><img src="<?php echo $this->getSkinUrl(); ?>images/WAIS.gif" alt="" style="width: 131px;"></a></li>
                <li><a href="#!" style="margin-right: 0px;"><img src="<?php echo $this->getSkinUrl(); ?>images/logo1.png" alt="" style="width: 155px;"></a></li>
            </ul>
        </div>
    </div><!--end-featured-brand-->
    <div class="testimonials">
        <div class="container" >
            <h2 class="tite">Testimonies</h2>
            <div id="testimoni-carousel" class="pull-left" style="width:94%; margin:auto;padding-left: 12px;">
                <div class="item">
                    <div >
                        <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                    </div>
                    <h3 class="profile-name">SARAH STOREY</h3>
                    <span class="win">72 TIME WORLD CHAMPION</span>
                    <div class="quote">
                        <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                    </div>
                </div>
                <div class="item">
                    <div >
                        <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                    </div>
                    <h3 class="profile-name">SARAH STOREY</h3>
                    <span class="win">72 TIME WORLD CHAMPION</span>
                    <div class="quote">
                        <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                    </div>
                </div>
                <div class="item">
                    <div >
                        <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                    </div>
                    <h3 class="profile-name">SARAH STOREY</h3>
                    <span class="win">72 TIME WORLD CHAMPION</span>
                    <div class="quote">
                        <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                    </div>
                </div>
                <div class="item">
                    <div >
                        <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                    </div>
                    <h3 class="profile-name">SARAH STOREY</h3>
                    <span class="win">72 TIME WORLD CHAMPION</span>
                    <div class="quote">
                        <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                    </div>
                </div>
                <div class="item">
                    <div >
                        <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                    </div>
                    <h3 class="profile-name">SARAH STOREY</h3>
                    <span class="win">72 TIME WORLD CHAMPION</span>
                    <div class="quote">
                        <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                    </div>
                </div>
                <div class="item">
                    <div >
                        <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                    </div>
                    <h3 class="profile-name">SARAH STOREY</h3>
                    <span class="win">72 TIME WORLD CHAMPION</span>
                    <div class="quote">
                        <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                    </div>
                </div>
                <div class="item">
                    <div >
                        <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                    </div>
                    <h3 class="profile-name">SARAH STOREY</h3>
                    <span class="win">72 TIME WORLD CHAMPION</span>
                    <div class="quote">
                        <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                    </div>
                </div>
                <div class="item">
                    <div >
                        <img src="<?php echo $this->getSkinUrl(); ?>images/sarahstorey.jpg" alt="">
                    </div>
                    <h3 class="profile-name">SARAH STOREY</h3>
                    <span class="win">72 TIME WORLD CHAMPION</span>
                    <div class="quote">
                        <span>I’ve chosen InfoCrank to ride my attempted World Hour Record because it’s the only power meter on the market that reliably measures both left and right power data, every time</span>
                    </div>
                </div>
            </div>
        </div>
    </div><!--end-testimpnials-->
</section><!--end-content-->