<div class="footer-links" id="sitemenu-<?php echo $this->getMenuCategory();?>">
    <?php echo $this->getMenu(); ?>
</div>

<script type="text/javascript">
//<![CDATA[
jQuery( document ).ready( function ( $ ) {
    // add `active` class to parents of current page item
    $('#sitemenu-<?php echo $this->getMenuCategory();?> li.current').parents('#sitemenu-<?php echo $this->getMenuCategory();?> li').addClass('active');
} );
//]]>
</script>
