<?php

$_level = $this->getLevel();
$_items = $this->getItems(); ?>

<ul class="catalog level-<?php echo $_level ?>">
    <?php foreach ( $_items as $_item ) :

    $_has_child  = $_item->getHasChild();
    $_is_current = $_item->getIsCurrent();
    $_is_first   = $_item->getIsFirst();
    $_is_last    = $_item->getIsLast();

    $_class  = 'level-'. $_level;
    $_class .= $_has_child ? ' parent' : '';
    $_class .= $_is_current ? ' current' : '';
    $_class .= $_is_last ? ' last' : ( $_is_first ? ' first' : '' );

    ?>
    <li class="<?php echo $_class ?> item-pro-<?php echo $_item->getEntityId() ?>">
        <a target="<?php echo $_item->getTarget() ? $_item->getTarget() : '_self' ?>" href="<?php echo $_item->getProductUrl() ?>"><span><?php echo $_item->getName() ?></span></a></li>
    <?php endforeach; ?>
</ul>
