<?php //$navColection = Mage::helper('sitemenu')->getWPMenu('Main Top Menu'); ?>
<?php echo Mage::helper('sitemenu')->getWPMenuHtml('Main Top Menu'); ?>
<!--<ul class="sitemenu level-1">
	<?php /*foreach($navColection as $item): ?>
		<li class="level-1<?php echo ' ' . $item['class']; ?>"><a href="<?php echo $item['url']; ?>"><?php echo $this->__($item['title']); ?></a></li>
	<?php endforeach;*/ ?>
</ul>-->